### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by lexavey** [khantsithu1998/bypass-react-native-emulator-detection#1]
C:\App\Frida>frida --codeshare khantsithu1998/bypass-react-native-emulator-detection -U -f com.shopee.id
     ____
    / _  |   Frida 16.0.8 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to Nexus 5 (id=127.0.0.1:58526)
Spawned `com.shopee.id`. Resuming main thread!
[Nexus 5::com.shopee.id ]-> [-] Error Detected
Error: java.lang.ClassNotFoundException: Didn't find class "com.learnium.RNDeviceInfo.RNDeviceModule" on path: DexPathList[[zip file "/data/app/~~aEWabnUYW8nHzY7gwLwaew==/com.shopee.id-t3uz-d7BSESt6GVG7QwDCw==/base.apk", zip file "/data/app/~~aEWabnUYW8nHzY7gwLwaew==/com.shopee.id-t3uz-d7BSESt6GVG7QwDCw==/split_config.mdpi.apk", zip file "/data/app/~~aEWabnUYW8nHzY7gwLwaew==/com.shopee.id-t3uz-d7BSESt6GVG7QwDCw==/split_config.x86_64.apk", zip file "/data/app/~~aEWabnUYW8nHzY7gwLwaew==/com.shopee.id-t3uz-d7BSESt6GVG7QwDCw==/split_dfpluginquic.apk", zip file "/data/app/~~aEWabnUYW8nHzY7gwLwaew==/com.shopee.id-t3uz-d7BSESt6GVG7QwDCw==/split_dfpluginquic.config.mdpi.apk", zip file "/data/app/~~aEWabnUYW8nHzY7gwLwaew==/com.shopee.id-t3uz-d7BSESt6GVG7QwDCw==/split_dfpluginshopee15.apk", zip file "/data/app/~~aEWabnUYW8nHzY7gwLwaew==/com.shopee.id-t3uz-d7BSESt6GVG7QwDCw==/split_dfpluginshopee15.config.mdpi.apk", zip file "/data/app/~~aEWabnUYW8nHzY7gwLwaew==/com.shopee.id-t3uz-d7BSESt6GVG7QwDCw==/split_dfpluginshopee16.apk", zip file "/data/app/~~aEWabnUYW8nHzY7gwLwaew==/com.shopee.id-t3uz-d7BSESt6GVG7QwDCw==/split_dfpluginshopee16.config.mdpi.apk", zip file "/data/app/~~aEWabnUYW8nHzY7gwLwaew==/com.shopee.id-t3uz-d7BSESt6GVG7QwDCw==/split_dfpluginshopee8.apk", zip file "/data/app/~~aEWabnUYW

**Comment by khantsithu1998** [comment]
This error is because the Shopee App does not use react-native-device-info. This script is for bypassing the detection of emulators using react-native-device-info, which is why it is causing the error.
